language: cpp
sudo: required
dist: bionic
git:
  depth: 1
env:
  global:
  - BUILD_CONFIG=Release
  - MSBUILD_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
matrix:
  include:
  - name: "Windows 10"
    os: windows
    env:
    - VCPKG_ROOT=/c/vcpkg
    - VCPKG_DEFAULT_TRIPLET=x86-windows-static
    - VCPKG_LIBS="lua[cpp]"
    - VCPKG_CACHE_ZIP_URL=https://github.com/kevinlul/edopro-vcpkg-cache/raw/master/installed-core.zip
  - name: "Bionic GCC7"
    os: linux
    compiler: gcc
  - name: "Bionic LLVM7"
    os: linux
    compiler: clang
  - name: "Mojave"
    os: osx
    osx_image: xcode10.3
    env: MACOSX_DEPLOYMENT_TARGET=10.11
install: ./travis/install-lua.sh
script: ./travis/build-cmake.sh
#deploy:
#- provider: releases
#  api_key: $OAUTH_TOKEN
#  file:
#  - bin/release/ocgcore.dll
#  - bin/release/libocgcore.dylib
#  - bin/release/libocgcore.so
#  skip_cleanup: true
#  draft: true
#  overwrite: true
#- provider: releases
#  api_key: $OAUTH_TOKEN
#  file:
#  - bin/release/ocgcore.dll
#  - bin/release/libocgcore.dylib
#  - bin/release/libocgcore.so
#  skip_cleanup: true
#  on:
#    tags: true
